; Matomo configuration
matomoURL = 'https://matomo.semcosoft.com/'
tokenAuth = 'e2f2253358cbc162b1a4032a2d41cd2a'

; SMTP credentials
smtp_encryption = 'ssl'
smtp_server = 'smtp.gmail.com'
smtp_email = 'matomoexpert@gmail.com'
smtp_pass = 'rlkj wnmg eumw lwmp'
smtp_name = 'Matomo Expert'
smtp_port = 465

; Recipients
emails[] = 'sadafashraf6037@gmail.com'
emails[] = 'matomo-reporting@semcosoft.com'

; Email titles and subjects
title = "eLearning Weekly Performance Report"
subject = "eLearning Weekly Performance Report"
body = "Please find attached the eLearning Weekly performance report in PDF format for your review. The report contains detailed insights and metrics for the past month."
reportName = "eLearning - Weekly Report.pdf"
